cdn_provider: ''
region_wells-sidebar_first: ''
_core:
  default_config_hash: 8Kd7wP_1eLByvuacvFyVnjKNv0THG9DHOYykRgzGjY8
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://discoverygarden-vsphere-i8-search.dgi/themes/contrib/dgi_i8_base/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  dgi_i8_base: 8000
table_responsive: '-1'
region_wells:
  navigation: ''
  header: ''
  header_left: ''
  header_center: ''
  header_right: ''
  sidr: ''
  sidr_bottom: ''
  highlighted: ''
  help: ''
  viewer: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  pre_footer: ''
  footer: ''
  footer_bottom: ''
  collection_metadata_and_actions: ''
  search_facet_header: ''
cdn_theme: ''
cdn_cache_ttl_versions: 0
cdn_cache_ttl_themes: 0
cdn_cache_ttl_assets: 0
cdn_cache_ttl_library: 0
reset_http_request_cache: ''
table: ''
secondary_logo: 'public://Screen Shot 2020-07-21 at 11.26.47 AM.png'
popover_placement: bottom
popover_html: 1
popover_enabled: 0
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
