preset_accent_color: custom
preset_focus_color: accent
enable_darkmode: false
classic_toolbar: vertical
icon_default: false
icon_path: themes/contrib/dgi_i8_base/DG+Coaster+Blue.png
high_contrast_mode: false
third_party_settings:
  shortcut:
    module_link: true
_core:
  default_config_hash: CEHTCpo0zzrZOJNa9_M2R_HdYKrq3v1zlRVCf66hh7U
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
favicon:
  use_default: false
  path: themes/contrib/dgi_i8_base/DG+Coaster+Blue.png
  mimetype: image/png
accent_color: '#00436A'
focus_color: ''
icon_upload: ''
