schemas:
  bootstrap: 8000
  dgi_i8_base: 8000
  wmc_i8_subtheme: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: themes/contrib/wmc_i8_subtheme/favicon.ico
  url: 'http://jojo-vsphere-wmc-46.dgi/themes/contrib/wmc_i8_subtheme/favicon-white.png'
  use_default: 0
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: themes/contrib/wmc_i8_subtheme/logo.png
  url: ''
  use_default: 0
use_default_footer_logo: 0
footer_logo_path: themes/contrib/wmc_i8_subtheme/footer_logo.png
region_wells:
  navigation: ''
  header: ''
  header_left: ''
  header_center: ''
  header_right: ''
  sidr: ''
  sidr_bottom: ''
  highlighted: ''
  help: ''
  viewer: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  pre_footer: ''
  footer: ''
  footer_bottom: ''
  navigation_collapsible: ''
  navigation_collapsible_search: ''
  basic_footer_columns: ''
  basic_footer_logo_section: ''
  collection_facets_grid: ''
  collection_facets_list: ''
  collection_metadata_and_actions: ''
  grid_facets: ''
  list_facets: ''
  meta: ''
  object_page_split_sidebar: ''
  search_facet_header: ''
reset_http_request_cache: ''
table: ''
